import os

from dotenv import load_dotenv

load_dotenv()

CORE_DEVS_CHANNEL_ID = int(os.environ["CORE_DEVS_CHANNEL_ID"])
GENERAL_CHANNEL_ID = int(os.environ["GENERAL_CHANNEL_ID"])
SCHEDULED_EVENT_CHANNEL_ID = int(os.environ["SCHEDULED_EVENT_CHANNEL_ID"])
DISCORD_TOKEN = os.environ["DISCORD_TOKEN"]
CALENDAR_URL = os.environ["CALENDAR_URL"]
NOTES_LINK = os.environ["NOTES_LINK"]
REACT_FOR_MEETINGS_NOTIFICATION_MESSAGE_ID = int(
    os.environ["REACT_FOR_MEETINGS_NOTIFICATION_MESSAGE_ID"]
)
MEETING_WATCHERS_ROLE_ID = int(os.environ["MEETING_WATCHERS_ROLE_ID"])
